POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin-8@email.com",
    "password": "Abc123!@#"
}

###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "admin-8@email.com",
    "password": "Abc123!@#"
}

###
GET http://localhost:3000/users/2

###
GET http://localhost:3000/users?email=admin-4@email.com

###
DELETE http://localhost:3000/users/4

###
PATCH http://localhost:3000/users/3
Content-Type: application/json

{
    "email": "user@email.com"
}